baseurl = "http://matt.routleynet.org/"
relativeurls = true
enableEmoji = true
languageCode = "en-ca"
title = "Various Contrivances"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Consulting"
    url = "/consulting/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mroutley"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/mroutley"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/matthew-routley-065abb77/"
[[menu.main]]
    name = "Micro.blog"
    url = "https://micro.blog/mroutley"
    rel = "me"

[params]
    description = "An internet wunderkammer."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

